platform :ios, '10.0'

target 'CurrencyChecker' do
  use_frameworks!
  pod 'ReactorKit'
  pod 'RxDataSources'
  pod "RxSwiftExt"
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxCodable'
  pod 'Moya/RxSwift'
  pod 'Then'
  pod 'SwiftLint'

  target 'CurrencyCheckerTests' do
    inherit! :search_paths
    pod 'RxBlocking'
    pod 'RxTest', '~> 4.0'
    pod 'Quick'
    pod 'Nimble'
   
  end

  target 'CurrencyCheckerUITests' do
    inherit! :search_paths
  end
end
