disabled_rules:
- conditional_returns_on_newline
- discouraged_object_literal
- explicit_acl
- explicit_top_level_acl
- explicit_type_interface
- explicit_enum_raw_value 
- no_extension_access_modifier
- no_grouping_extension
- prefixed_toplevel_constant
- sorted_imports
- todo
- file_header
- force_unwrapping
- force_try
- quick_discouraged_call
- implicitly_unwrapped_optional

opt_in_rules:
- attributes
- array_init
- closure_end_indentation
- closure_spacing
- conditional_returns_on_newline
- contains_over_first_not_nil
- convenience_type
- discouraged_optional_boolean
- discouraged_optional_collection
- dynamic_inline
- empty_count
- empty_string
- empty_xctest_method
- explicit_init
- extension_access_modifier
- fallthrough
- fatal_error_message
- file_header
- file_name
- first_where
- function_default_parameter_at_end
- implicit_return
- joined_default_parameter
- large_tuple
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
- mark
- modifier_order
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- nimble_operator
- number_separator
- object_literal
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- private_action
- private_outlet
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_nil_coalescing
- required_enum_case
- shorthand_operator
- single_test_class
- sorted_first_last
- strict_fileprivate
- switch_case_on_newline
- trailing_closure
- unavailable_function
- unneeded_parentheses_in_closure_argument
- untyped_error_in_catch
- vertical_parameter_alignment_on_call
- yoda_condition
attributes:
  always_on_same_line: ["@discardableResult", "@objc", "@IBAction", "@IBDesignable"]

line_length: 
  warning: 160
  ignores_function_declarations: true
  ignores_comments: true

nesting:
  type_level: 2

type_body_length: 500 

file_length: 700

function_parameter_count: 6

warning_threshold: 1


