platform :ios, '10.0'

target 'CurrencyChecker' do
  use_frameworks!
  pod 'ReactorKit'
  pod 'RxDataSources'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'Then'

  target 'CurrencyCheckerTests' do
    inherit! :search_paths
    pod 'RxBlocking'
    pod 'Quick'
    pod 'Nimble'
   
  end

  target 'CurrencyCheckerUITests' do
    inherit! :search_paths

  end

end
